namespace :insert_race_horse do
  require_relative '../../app/helpers/disassemble_race_horse.rb'
  require_relative '../../app/models/race_horse.rb'
  require_relative '../../app/models/application_record.rb'
  RACE_HORSE_TARGET_FILE = "db/resources/race_horse/**/*"

  desc "race_horse"
  task :race_horse => :environment do
    targetFilesPath = Dir.glob RACE_HORSE_TARGET_FILE
    targetFilesPath.each do |filePath|
      race_horses = []
      File.open(filePath) do |file|
        if File::ftype(filePath) == "directory"
          next
        end
        file.each_line do |line|
          disassemble_race_horse = DisassembleRaceHorse.new(line)
          race_horse = RaceHorse.new(
              race_key_course_code: disassembleRaceHorse.getRaceKeyCourseCode,
              race_key_year: disassembleRaceHorse.getRaceKeyYear,
              race_key_times: disassembleRaceHorse.getRaceKeyTimes,
              race_key_day: disassembleRaceHorse.getRaceKeyDay,
              race_key_number_of_race: disassembleRaceHorse.getRaceKeyNumberOfRace,
              race_horse_number: disassembleRaceHorse.getRaceHorseNumber,
              horse_pedigree_registration_code: disassembleRaceHorse.getHorsePedigreeRegistrationCode,
              horse_name: disassembleRaceHorse.getHorseName,
              idm: disassembleRaceHorse.getIdm,
              jockey_index: disassembleRaceHorse.getJockeyIndex,
              infomation_index: disassembleRaceHorse.getInfomationIndex,
              reserve_one: disassembleRaceHorse.getReserveOne,
              reserve_two: disassembleRaceHorse.getReserveTwo,
              reseve_three: disassembleRaceHorse.getReseveThree,
              composite_index: disassembleRaceHorse.getCompositeIndex,
              leg_quality: disassembleRaceHorse.getLegQuality,
              distance_aptitude: disassembleRaceHorse.getDistanceAptitude,
              rising_degree: disassembleRaceHorse.getRisingDegree,
              rotation: disassembleRaceHorse.getRotation,
              standard_odds: disassembleRaceHorse.getStandardOdds,
              standard_popularity_rank: disassembleRaceHorse.getStandardPopularityRank,
              standard_show_odds: disassembleRaceHorse.getStandardShowOdds,
              standard_show_popularity_rank: disassembleRaceHorse.getStandardShowPopularityRank,
              specific_info_excellent: disassembleRaceHorse.getSpecificInfoExcellent,
              specific_info_good: disassembleRaceHorse.getSpecificInfoGood,
              specific_info_fair: disassembleRaceHorse.getSpecificInfoFair,
              specific_info_bad: disassembleRaceHorse.getSpecificInfoBad,
              specific_info_failure: disassembleRaceHorse.getSpecificInfoFailure ,
              composite_info_excellent: disassembleRaceHorse.getCompositeInfoExcellent,
              composite_info_good: disassembleRaceHorse.getCompositeInfoGood,
              composite_info_fair: disassembleRaceHorse.getCompositeInfoFair,
              composite_info_bad: disassembleRaceHorse.getCompositeInfoBad,
              composite_info_failure: disassembleRaceHorse.getCompositeInfoFailure ,
              popularity_index: disassembleRaceHorse.getPopularityIndex,
              training_index: disassembleRaceHorse.getTrainingIndex,
              racing_stable_index: disassembleRaceHorse.getRacingStableIndex,
              training_arrow_code: disassembleRaceHorse.getTrainingArrowCode,
              racing_stable_evaluation_code: disassembleRaceHorse.getRacingStableEvaluationCode,
              jockey_expected_confidence_rate: disassembleRaceHorse.getJockeyExpectedConfidenceRate,
              rushing_index: disassembleRaceHorse.getRushingIndex,
              hoof_code: disassembleRaceHorse.getHoofCode,
              heaviness_aptitude_code: disassembleRaceHorse.getHeavinessAptitudeCode,
              class_code: disassembleRaceHorse.getClassCode,
              reserve_four: disassembleRaceHorse.getReserveFour,
              blinker_code: disassembleRaceHorse.getBlinkerCode,
              jockey_name: disassembleRaceHorse.getJockeyName,
              burden_weight: disassembleRaceHorse.getBurdenWeight,
              apprentice_class: disassembleRaceHorse.getApprenticeClass,
              trainer_name: disassembleRaceHorse.getTrainerName,
              trainer_belong: disassembleRaceHorse.getTrainerBelong,
              other_data_link_key_prebious_run_1_race_score_key: disassembleRaceHorse.getOtherDataLinkKeyPrebiousRun1RaceScoreKey,
              other_data_link_key_prebious_run_2_race_score_key: disassembleRaceHorse.getOtherDataLinkKeyPrebiousRun2RaceScoreKey,
              other_data_link_key_prebious_run_3_race_score_key: disassembleRaceHorse.getOtherDataLinkKeyPrebiousRun3RaceScoreKey,
              other_data_link_key_prebious_run_4_race_score_key: disassembleRaceHorse.getOtherDataLinkKeyPrebiousRun4RaceScoreKey,
              other_data_link_key_prebious_run_5_race_score_key: disassembleRaceHorse.getOtherDataLinkKeyPrebiousRun5RaceScoreKey,
              other_data_link_key_prebious_run_1_race_key: disassembleRaceHorse.getOtherDataLinkKeyPrebiousRun1RaceKey,
              other_data_link_key_prebious_run_2_race_key: disassembleRaceHorse.getOtherDataLinkKeyPrebiousRun2RaceKey,
              other_data_link_key_prebious_run_3_race_key: disassembleRaceHorse.getOtherDataLinkKeyPrebiousRun3RaceKey,
              other_data_link_key_prebious_run_4_race_key: disassembleRaceHorse.getOtherDataLinkKeyPrebiousRun4RaceKey,
              other_data_link_key_prebious_run_5_race_key: disassembleRaceHorse.getOtherDataLinkKeyPrebiousRun5RaceKey,
              bracket_number: disassembleRaceHorse.getBracketNumber,
              reserve_five: disassembleRaceHorse.getReserveFive,
              mark_code_composite: disassembleRaceHorse.getMarkCodeComposite,
              mark_code_idm: disassembleRaceHorse.getMarkCodeIdm,
              mark_code_infomation: disassembleRaceHorse.getMarkCodeInfomation,
              mark_code_jockey: disassembleRaceHorse.getMarkCodeJockey,
              mark_code_racing_stable: disassembleRaceHorse.getMarkCodeRacingStable,
              mark_code_trainer: disassembleRaceHorse.getMarkCodeTrainer,
              mark_code_rushing: disassembleRaceHorse.getMarkCodeRushing,
              turf_aptitude_code: disassembleRaceHorse.getTurfAptitudeCode,
              dirt_aptitude_code: disassembleRaceHorse.getDirtAptitudeCode,
              jockey_code: disassembleRaceHorse.getJockeyCode,
              trainer_code: disassembleRaceHorse.getTrainerCode,
              reserve_six: disassembleRaceHorse.getReserveSix,
              winning_prize: disassembleRaceHorse.getWinningPrize,
              income_prize: disassembleRaceHorse.getIncomePrize,
              condition_class: disassembleRaceHorse.getConditionClass,
              expansion_forecast_data_ten_index: disassembleRaceHorse.getExpansionForecastDataTenIndex,
              expansion_forecast_data_pace_index: disassembleRaceHorse.getExpansionForecastDataPaceIndex,
              expansion_forecast_data_ricing_index: disassembleRaceHorse.getExpansionForecastDataRicingIndex,
              expansion_forecast_data_position_index: disassembleRaceHorse.getExpansionForecastDataPositionIndex,
              expansion_forecast_data_pace: disassembleRaceHorse.getExpansionForecastDataPace,
              expansion_forecast_data_halfway_ranking: disassembleRaceHorse.getExpansionForecastDataHalfwayRanking,
              expansion_forecast_data_halfway_difference: disassembleRaceHorse.getExpansionForecastDataHalfwayDifference,
              expansion_forecast_data_halfway_Inside_outside: disassembleRaceHorse.getExpansionForecastDataHalfwayInsideOutside,
              expansion_forecast_data_after_3f_time: disassembleRaceHorse.getExpansionForecastDataAfter3FTime,
              expansion_forecast_data_after_3f_difference: disassembleRaceHorse.getExpansionForecastDataAfter3FDifference,
              expansion_forecast_data_after_3f_Inside_outside: disassembleRaceHorse.getExpansionForecastDataAfter3FInsideOutside,
              expansion_forecast_data_goal_ranking: disassembleRaceHorse.getExpansionForecastDataGoalRanking,
              expansion_forecast_data_goal_difference: disassembleRaceHorse.getExpansionForecastDataGoalDifference,
              expansion_forecast_data_goal_Inside_outside: disassembleRaceHorse.getExpansionForecastDataGoalInsideOutside,
              expansion_forecast_data_expansion_symbol: disassembleRaceHorse.getExpansionForecastDataExpansionSymbol,
              distance_aptitude_two: disassembleRaceHorse.getDistanceAptitudeTwo,
              horse_weight_fixed: disassembleRaceHorse.getHorseWeightFixed ,
              horse_weight_gain_fixed: disassembleRaceHorse.getHorseWeightGainFixed ,
              cancel_flg: disassembleRaceHorse.getCancelFlg,
              gender_code: disassembleRaceHorse.getGenderCode,
              owner_name: disassembleRaceHorse.getOwnerName,
              owner_belong_code: disassembleRaceHorse.getOwnerBelongCode,
              horse_symbol_code: disassembleRaceHorse.getHorseSymbolCode,
              rushing_runking: disassembleRaceHorse.getRushingRunking,
              ls_index_runking: disassembleRaceHorse.getLsIndexRunking,
              ten_index_runking: disassembleRaceHorse.getTenIndexRunking,
              pace_index_runking: disassembleRaceHorse.getPaceIndexRunking,
              rising_index_runking: disassembleRaceHorse.getRisingIndexRunking,
              position_index_runking: disassembleRaceHorse.getPositionIndexRunking,
              jockey_expectation_victory_rate: disassembleRaceHorse.getJockeyExpectationVictoryRate,
              jockey_expectation_3_inside_rate: disassembleRaceHorse.getJockeyExpectation3InsideRate,
              transportation_class: disassembleRaceHorse.getTransportationClass,
              exercise: disassembleRaceHorse.getExercise,
              body_type: disassembleRaceHorse.getBodyType,
              total_body_type_one: disassembleRaceHorse.getTotalBodyTypeOne,
              total_body_type_two: disassembleRaceHorse.getTotalBodyTypeTwo,
              total_body_type_three: disassembleRaceHorse.getTotalBodyTypeThree,
              horse_special_mention_one: disassembleRaceHorse.getHorseSpecialMentionOne,
              horse_special_mention_two: disassembleRaceHorse.getHorseSpecialMentionTwo,
              horse_special_mention_three: disassembleRaceHorse.getHorseSpecialMentionThree,
              horse_start_index: disassembleRaceHorse.getHorseStartIndex,
              horse_departure_rate: disassembleRaceHorse.getHorseDepartureRate,
              running_before_reference: disassembleRaceHorse.getRunningBeforeReference,
              reference_riding_jockey_code: disassembleRaceHorse.getReferenceRidingJockeyCode,
              ten_thousand_ticket_index: disassembleRaceHorse.getTenThousandTicketIndex,
              ten_thousand_ticket_mark: disassembleRaceHorse.getTenThousandTicketMark,
              down_class_flg: disassembleRaceHorse.getDownClassFlg,
              rushing_type: disassembleRaceHorse.getRushingType,
              recreation_reason_code: disassembleRaceHorse.getRecreationReasonCode,
              flg: disassembleRaceHorse.getFlg,
              racing_stable_running_times: disassembleRaceHorse.getRacingStableRunningTimes,
              racing_stable_ymd: disassembleRaceHorse.getRacingStableYmd,
              racing_stable_days: disassembleRaceHorse.getRacingStableDays,
              grazing_destination: disassembleRaceHorse.getGrazingDestination,
              grazing_destination_rank: disassembleRaceHorse.getGrazingDestinationRank,
              racing_stable_rank: disassembleRaceHorse.getRacingStableRank
          )
          race_horses << race_horse
        end
      end
      RaceHorse.import race_horses
    end
  end
end
