# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20180211183828) do

  create_table "basic_horses", force: :cascade do |t|
    t.string "pedigree_register_code"
    t.string "horse_name"
    t.string "gender_code"
    t.string "coat_color_code"
    t.string "horse_symbol_code"
    t.string "pedigree_info_father_name"
    t.string "pedigree_info_mother_name"
    t.string "pedigree_info_maternal_father_name"
    t.date "pedigree_info_barth_on"
    t.date "pedigree_info_father_barth_on"
    t.date "pedigree_info_mother_barth_on"
    t.date "pedigree_info_maternal_father_barth_on"
    t.string "pedigree_info_owner_name"
    t.string "pedigree_info_owner_belong_code"
    t.string "pedigree_info_producer_name"
    t.string "pedigree_info_production_place_name"
    t.string "pedigree_info_register_del_flg"
    t.date "pedigree_info_data_ymd"
    t.string "pedigree_info_father_lineage_code"
    t.string "pedigree_info_maternal_father_lineage_code"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "holding_races", force: :cascade do |t|
    t.string "holding_race_key"
    t.string "race_key_course_code"
    t.string "race_key_year"
    t.string "race_key_times"
    t.string "race_key_day"
    t.date "date_ymd"
    t.string "holding_class"
    t.string "day_of_week"
    t.string "course_name"
    t.string "weather_code"
    t.string "turf_course_state_code"
    t.string "turf_course_Inside_state"
    t.string "turf_course_middle_state"
    t.string "turf_course_outside_state"
    t.string "turf_course_difference"
    t.string "linear_course_difference_must_inside"
    t.string "linear_course_difference_inside"
    t.string "linear_course_difference_middle"
    t.string "linear_course_difference_outside"
    t.string "linear_course_difference_must_outside"
    t.string "dirt_course_state_code"
    t.string "dirt_course_Inside_state"
    t.string "dirt_course_middle_state"
    t.string "dirt_course_outside_state"
    t.string "dirt_course_difference"
    t.string "data_class"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "past_race_results", force: :cascade do |t|
    t.string "race_key_course_code"
    t.string "race_key_year"
    t.string "race_key_times"
    t.string "race_key_day"
    t.string "race_key_number_of_race"
    t.string "race_key_horse_number"
    t.string "race_performance_pedigree_register_code"
    t.date "race_performance_date_ymd"
    t.string "race_performance_horse_name"
    t.integer "race_condition_distance"
    t.string "truck_turf_dirt_fault_code"
    t.string "truck_right_or_left"
    t.string "truck_inside_or_outside"
    t.integer "race_condition_riding_ground_condition"
    t.integer "race_condition_class"
    t.string "race_condition_requirement"
    t.integer "race_condition_symbol"
    t.integer "race_condition_weight"
    t.integer "race_condition_grade"
    t.string "race_condition_race_name"
    t.integer "race_condition_horse_count"
    t.string "race_condition_race_name_short"
    t.integer "horse_race_performance_ranking"
    t.integer "horse_race_performance_abnormal_classification"
    t.integer "horse_race_performance_time"
    t.integer "horse_race_performance_basis_weight"
    t.string "horse_race_performance_jockey_name"
    t.string "horse_race_performance_trainer_name"
    t.float "horse_race_performance_confirm_win_odds"
    t.integer "horse_race_performance_confirm_win_popular_rank"
    t.integer "jrdb_idm"
    t.integer "jrdb_primary_point"
    t.integer "jrdb_riding_ground_reference"
    t.integer "jrdb_pace"
    t.integer "jrdb_lagging"
    t.integer "jrdb_position_of_race"
    t.integer "jrdb_unfavorable"
    t.integer "jrdb_unfavorable_before"
    t.integer "jrdb_unfavorable_middle"
    t.integer "jrdb_unfavorable_after"
    t.integer "jrdb_race"
    t.integer "jrdb_course_removal"
    t.string "jrdb_rising_code"
    t.string "jrdb_class_code"
    t.integer "jrdb_horse_body_code"
    t.integer "jrdb_sign_code"
    t.string "jrdb_race_pace"
    t.string "jrdb_horse_pace"
    t.float "jrdb_ten_index"
    t.float "jrdb_rising_index_code"
    t.float "jrdb_pace_index"
    t.float "jrdb_race_pace_index"
    t.string "jrdb_first_second_horse_name"
    t.float "jrdb_first_second_horse_time_reference"
    t.float "jrdb_before_3f_time"
    t.float "jrdb_after_3f_time"
    t.string "jrdb_remarks"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "refund_bet_tickets", force: :cascade do |t|
    t.string "race_key_course_code"
    t.string "race_key_year"
    t.string "race_key_times"
    t.string "race_key_day"
    t.string "race_key_number_of_race"
    t.string "win_horse_number_1"
    t.integer "win_odds_1"
    t.string "win_horse_number_2"
    t.integer "win_odds_2"
    t.string "win_horse_number_3"
    t.integer "win_odds_3"
    t.string "show_horse_number_1"
    t.integer "show_odds_1"
    t.string "show_horse_number_2"
    t.integer "show_odds_2"
    t.string "show_horse_number_3"
    t.integer "show_odds_3"
    t.string "show_horse_number_4"
    t.integer "show_odds_4"
    t.string "show_horse_number_5"
    t.integer "show_odds_5"
    t.string "bracket_exacta_1_number_1"
    t.string "bracket_exacta_1_number_2"
    t.integer "bracket_exacta_1_odds"
    t.string "bracket_exacta_2_number_1"
    t.string "bracket_exacta_2_number_2"
    t.integer "bracket_exacta_2_odds"
    t.string "bracket_exacta_3_number_1"
    t.string "bracket_exacta_3_number_2"
    t.integer "bracket_exacta_3_odds"
    t.string "quinella_1_horse_number_1"
    t.string "quinella_1_horse_number_2"
    t.integer "quinella_1_odds"
    t.string "quinella_2_horse_number_1"
    t.string "quinella_2_horse_number_2"
    t.integer "quinella_2_odds"
    t.string "quinella_3_horse_number_1"
    t.string "quinella_3_horse_number_2"
    t.integer "quinella_3_odds"
    t.string "quinella_place_1_horse_number_1"
    t.string "quinella_place_1_horse_number_2"
    t.integer "quinella_place_1_odds"
    t.string "quinella_place_2_horse_number_1"
    t.string "quinella_place_2_horse_number_2"
    t.integer "quinella_place_2_odds"
    t.string "quinella_place_3_horse_number_1"
    t.string "quinella_place_3_horse_number_2"
    t.integer "quinella_place_3_odds"
    t.string "quinella_place_4_horse_number_1"
    t.string "quinella_place_4_horse_number_2"
    t.integer "quinella_place_4_odds"
    t.string "quinella_place_5_horse_number_1"
    t.string "quinella_place_5_horse_number_2"
    t.integer "quinella_place_5_odds"
    t.string "quinella_place_6_horse_number_1"
    t.string "quinella_place_6_horse_number_2"
    t.integer "quinella_place_6_odds"
    t.string "quinella_place_7_horse_number_1"
    t.string "quinella_place_7_horse_number_2"
    t.integer "quinella_place_7_odds"
    t.string "exacta_1_horse_number_1"
    t.string "exacta_1_horse_number_2"
    t.integer "exacta_1_odds"
    t.string "exacta_2_horse_number_1"
    t.string "exacta_2_horse_number_2"
    t.integer "exacta_2_odds"
    t.string "exacta_3_horse_number_1"
    t.string "exacta_3_horse_number_2"
    t.integer "exacta_3_odds"
    t.string "exacta_4_horse_number_1"
    t.string "exacta_4_horse_number_2"
    t.integer "exacta_4_odds"
    t.string "exacta_5_horse_number_1"
    t.string "exacta_5_horse_number_2"
    t.integer "exacta_5_odds"
    t.string "exacta_6_horse_number_1"
    t.string "exacta_6_horse_number_2"
    t.integer "exacta_6_odds"
    t.string "trio_1_horse_number_1"
    t.string "trio_1_horse_number_2"
    t.string "trio_1_horse_number_3"
    t.integer "trio_1_odds"
    t.string "trio_2_horse_number_1"
    t.string "trio_2_horse_number_2"
    t.string "trio_2_horse_number_3"
    t.integer "trio_2_odds"
    t.string "trio_3_horse_number_1"
    t.string "trio_3_horse_number_2"
    t.string "trio_3_horse_number_3"
    t.integer "trio_3_odds"
    t.string "trifecta_1_horse_number_1"
    t.string "trifecta_1_horse_number_2"
    t.string "trifecta_1_horse_number_3"
    t.integer "trifecta_1_odds"
    t.string "trifecta_2_horse_number_1"
    t.string "trifecta_2_horse_number_2"
    t.string "trifecta_2_horse_number_3"
    t.integer "trifecta_2_odds"
    t.string "trifecta_3_horse_number_1"
    t.string "trifecta_3_horse_number_2"
    t.string "trifecta_3_horse_number_3"
    t.integer "trifecta_3_odds"
    t.string "trifecta_4_horse_number_1"
    t.string "trifecta_4_horse_number_2"
    t.string "trifecta_4_horse_number_3"
    t.integer "trifecta_4_odds"
    t.string "trifecta_5_horse_number_1"
    t.string "trifecta_5_horse_number_2"
    t.string "trifecta_5_horse_number_3"
    t.integer "trifecta_5_odds"
    t.string "trifecta_6_horse_number_1"
    t.string "trifecta_6_horse_number_2"
    t.string "trifecta_6_horse_number_3"
    t.integer "trifecta_6_odds"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "registered_horses", force: :cascade do |t|
    t.string "race_key_course_code"
    t.string "race_key_year"
    t.string "race_key_times"
    t.string "race_key_day"
    t.string "race_key_number_of_race"
    t.string "horse_name_code"
    t.string "horse_pedigree_registration_code"
    t.string "horse_name"
    t.string "horse_gender_code"
    t.string "horse_symbol_code"
    t.string "blinker_code"
    t.string "jockey_name"
    t.integer "burden_weight"
    t.string "apprentice_class"
    t.string "trainer_name"
    t.string "trainer_belong"
    t.float "idm"
    t.string "rising_degree"
    t.string "rotation"
    t.string "leg_quality"
    t.string "distance_aptitude"
    t.string "distance_aptitude_second"
    t.string "turf_aptitude_code"
    t.string "dart_aptitude_code"
    t.string "heaviness_aptitude_code"
    t.string "hoof_code"
    t.string "class_code"
    t.string "coat_color_code"
    t.string "other_data_link_key_prebious_run_1_race_score_key"
    t.string "other_data_link_key_prebious_run_2_race_score_key"
    t.string "other_data_link_key_prebious_run_3_race_score_key"
    t.string "other_data_link_key_prebious_run_4_race_score_key"
    t.string "other_data_link_key_prebious_run_5_race_score_key"
    t.string "other_data_link_key_prebious_run_1_race_key"
    t.string "other_data_link_key_prebious_run_2_race_key"
    t.string "other_data_link_key_prebious_run_3_race_key"
    t.string "other_data_link_key_prebious_run_4_race_key"
    t.string "other_data_link_key_prebious_run_5_race_key"
    t.string "jockey_code"
    t.string "trainer_code"
    t.integer "winning_prize"
    t.integer "income_prize"
    t.string "condition_class"
    t.string "exercise"
    t.string "body_type"
    t.string "body_type_total_1"
    t.string "body_type_total_2"
    t.string "body_type_total_3"
    t.string "horse_special_mention_1"
    t.string "horse_special_mention_2"
    t.string "horse_special_mention_3"
    t.float "expansion_forecast_data_ten_index"
    t.float "expansion_forecast_data_pace_index"
    t.float "expansion_forecast_data_ricing_index"
    t.float "expansion_forecast_data_position_index"
    t.float "horse_start_index"
    t.float "horse_lagging_rate"
    t.string "running_before_reference"
    t.string "reference_riding_horse_code"
    t.string "data_partition"
    t.string "leading_rank"
    t.string "reserve"
    t.datetime "deleted_at"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "tv_programs", force: :cascade do |t|
    t.string "race_key_year"
    t.string "race_key_times"
    t.string "race_key_day"
    t.string "race_key_number_of_race"
    t.date "race_key_horse_number"
    t.string "race_condition_time_of_launch"
    t.integer "race_condition_distance"
    t.string "truck_turf_dirt_fault_code"
    t.string "truck_right_or_left"
    t.string "truck_inside_or_outside"
    t.integer "race_condition_class"
    t.string "race_condition_requirement"
    t.integer "race_condition_symbol"
    t.integer "race_condition_weight"
    t.integer "race_condition_grade"
    t.string "race_condition_race_name"
    t.string "race_condition_times"
    t.integer "race_condition_horse_count"
    t.string "race_condition_course"
    t.string "race_condition_holding_class"
    t.string "race_condition_race_name_short"
    t.string "race_condition_race_name_nine"
    t.string "data_class"
    t.integer "one_prize_money"
    t.integer "two_prize_money"
    t.integer "three_prize_money"
    t.integer "four_prize_money"
    t.integer "five_prize_money"
    t.integer "one_budget_cash_prize"
    t.integer "two_budget_cash_prize"
    t.string "ticket＿release_flg"
    t.string "win_five_flg"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

end
