class CreateStandardOdds < ActiveRecord::Migration[5.1]
  def change
    create_table :standard_odds do |t|

      t.string :race_key_course_code
      t.string :race_key_year
      t.string :race_key_times
      t.string :race_key_day
      t.string :race_key_number_of_race
      t.integer :registered_number
      t.float :win_odds1
      t.float :win_odds2
      t.float :win_odds3
      t.float :win_odds4
      t.float :win_odds5
      t.float :win_odds6
      t.float :win_odds7
      t.float :win_odds8
      t.float :win_odds9
      t.float :win_odds10
      t.float :win_odds11
      t.float :win_odds12
      t.float :win_odds13
      t.float :win_odds14
      t.float :win_odds15
      t.float :win_odds16
      t.float :win_odds17
      t.float :win_odds18
      t.float :show_odds1
      t.float :show_odds2
      t.float :show_odds3
      t.float :show_odds4
      t.float :show_odds5
      t.float :show_odds6
      t.float :show_odds7
      t.float :show_odds8
      t.float :show_odds9
      t.float :show_odds10
      t.float :show_odds11
      t.float :show_odds12
      t.float :show_odds13
      t.float :show_odds14
      t.float :show_odds15
      t.float :show_odds16
      t.float :show_odds17
      t.float :show_odds18
      t.float :quinella1
      t.float :quinella2
      t.float :quinella3
      t.float :quinella4
      t.float :quinella5
      t.float :quinella6
      t.float :quinella7
      t.float :quinella8
      t.float :quinella9
      t.float :quinella10
      t.float :quinella11
      t.float :quinella12
      t.float :quinella13
      t.float :quinella14
      t.float :quinella15
      t.float :quinella16
      t.float :quinella17
      t.float :quinella18
      t.float :quinella19
      t.float :quinella20
      t.float :quinella21
      t.float :quinella22
      t.float :quinella23
      t.float :quinella24
      t.float :quinella25
      t.float :quinella26
      t.float :quinella27
      t.float :quinella28
      t.float :quinella29
      t.float :quinella30
      t.float :quinella31
      t.float :quinella32
      t.float :quinella33
      t.float :quinella34
      t.float :quinella35
      t.float :quinella36
      t.float :quinella37
      t.float :quinella38
      t.float :quinella39
      t.float :quinella40
      t.float :quinella41
      t.float :quinella42
      t.float :quinella43
      t.float :quinella44
      t.float :quinella45
      t.float :quinella46
      t.float :quinella47
      t.float :quinella48
      t.float :quinella49
      t.float :quinella50
      t.float :quinella51
      t.float :quinella52
      t.float :quinella53
      t.float :quinella54
      t.float :quinella55
      t.float :quinella56
      t.float :quinella57
      t.float :quinella58
      t.float :quinella59
      t.float :quinella60
      t.float :quinella61
      t.float :quinella62
      t.float :quinella63
      t.float :quinella64
      t.float :quinella65
      t.float :quinella66
      t.float :quinella67
      t.float :quinella68
      t.float :quinella69
      t.float :quinella70
      t.float :quinella71
      t.float :quinella72
      t.float :quinella73
      t.float :quinella74
      t.float :quinella75
      t.float :quinella76
      t.float :quinella77
      t.float :quinella78
      t.float :quinella79
      t.float :quinella80
      t.float :quinella81
      t.float :quinella82
      t.float :quinella83
      t.float :quinella84
      t.float :quinella85
      t.float :quinella86
      t.float :quinella87
      t.float :quinella88
      t.float :quinella89
      t.float :quinella90
      t.float :quinella91
      t.float :quinella92
      t.float :quinella93
      t.float :quinella94
      t.float :quinella95
      t.float :quinella96
      t.float :quinella97
      t.float :quinella98
      t.float :quinella99
      t.float :quinella100
      t.float :quinella101
      t.float :quinella102
      t.float :quinella103
      t.float :quinella104
      t.float :quinella105
      t.float :quinella106
      t.float :quinella107
      t.float :quinella108
      t.float :quinella109
      t.float :quinella110
      t.float :quinella111
      t.float :quinella112
      t.float :quinella113
      t.float :quinella114
      t.float :quinella115
      t.float :quinella116
      t.float :quinella117
      t.float :quinella118
      t.float :quinella119
      t.float :quinella120
      t.float :quinella121
      t.float :quinella122
      t.float :quinella123
      t.float :quinella124
      t.float :quinella125
      t.float :quinella126
      t.float :quinella127
      t.float :quinella128
      t.float :quinella129
      t.float :quinella130
      t.float :quinella131
      t.float :quinella132
      t.float :quinella133
      t.float :quinella134
      t.float :quinella135
      t.float :quinella136
      t.float :quinella137
      t.float :quinella138
      t.float :quinella139
      t.float :quinella140
      t.float :quinella141
      t.float :quinella142
      t.float :quinella143
      t.float :quinella144
      t.float :quinella145
      t.float :quinella146
      t.float :quinella147
      t.float :quinella148
      t.float :quinella149
      t.float :quinella150
      t.float :quinella151
      t.float :quinella152
      t.float :quinella153

      t.timestamps
    end
  end
end
