class CreateRaceHorseExtentions < ActiveRecord::Migration[5.1]
  def change
    create_table :race_horse_extentions do |t|
      t.string :race_key_course_code
      t.string :race_key_year
      t.string :race_key_times
      t.string :race_key_day
      t.string :race_key_number_of_race
      t.string :race_horse_number
      t.integer :jra_achievement_1
      t.integer :jra_achievement_2
      t.integer :jra_achievement_3
      t.integer :jra_achievement_4
      t.integer :interaction_achievement_1
      t.integer :interaction_achievement_2
      t.integer :interaction_achievement_3
      t.integer :interaction_achievement_4
      t.integer :other_achievement_1
      t.integer :other_achievement_2
      t.integer :other_achievement_3
      t.integer :other_achievement_4
      t.integer :turf_dirt_fault_achievement_1
      t.integer :turf_dirt_fault_achievement_2
      t.integer :turf_dirt_fault_achievement_3
      t.integer :turf_dirt_fault_achievement_4
      t.integer :turf_dirt_fault_distance_achievement_1
      t.integer :turf_dirt_fault_distance_achievement_2
      t.integer :turf_dirt_fault_distance_achievement_3
      t.integer :turf_dirt_fault_distance_achievement_4
      t.integer :truck_distance_achievement_1
      t.integer :truck_distance_achievement_2
      t.integer :truck_distance_achievement_3
      t.integer :truck_distance_achievement_4
      t.integer :rotation_achievement_1
      t.integer :rotation_achievement_2
      t.integer :rotation_achievement_3
      t.integer :rotation_achievement_4
      t.integer :circle_achievement_1
      t.integer :circle_achievement_2
      t.integer :circle_achievement_3
      t.integer :circle_achievement_4
      t.integer :jockey_achievement_1
      t.integer :jockey_achievement_2
      t.integer :jockey_achievement_3
      t.integer :jockey_achievement_4
      t.integer :good_field_achievement_1
      t.integer :good_field_achievement_2
      t.integer :good_field_achievement_3
      t.integer :good_field_achievement_4
      t.integer :bad_field_achievement_1
      t.integer :bad_field_achievement_2
      t.integer :bad_field_achievement_3
      t.integer :bad_field_achievement_4
      t.integer :fail_field_achievement_1
      t.integer :fail_field_achievement_2
      t.integer :fail_field_achievement_3
      t.integer :fail_field_achievement_4
      t.integer :s_pace_achievement_1
      t.integer :s_pace_achievement_2
      t.integer :s_pace_achievement_3
      t.integer :s_pace_achievement_4
      t.integer :m_pace_achievement_1
      t.integer :m_pace_achievement_2
      t.integer :m_pace_achievement_3
      t.integer :m_pace_achievement_4
      t.integer :h_pace_achievement_1
      t.integer :h_pace_achievement_2
      t.integer :h_pace_achievement_3
      t.integer :h_pace_achievement_4
      t.integer :season_achievement_1
      t.integer :season_achievement_2
      t.integer :season_achievement_3
      t.integer :season_achievement_4
      t.integer :bracket_achievement_1
      t.integer :bracket_achievement_2
      t.integer :bracket_achievement_3
      t.integer :bracket_achievement_4
      t.integer :jockey_distance_achievement_1
      t.integer :jockey_distance_achievement_2
      t.integer :jockey_distance_achievement_3
      t.integer :jockey_distance_achievement_4
      t.integer :jockey_distance_truck_achievement_one_1
      t.integer :jockey_distance_truck_achievement_one_2
      t.integer :jockey_distance_truck_achievement_one_3
      t.integer :jockey_distance_truck_achievement_one_4
      t.integer :jockey_trainer_achievement_1
      t.integer :jockey_trainer_achievement_2
      t.integer :jockey_trainer_achievement_3
      t.integer :jockey_trainer_achievement_4
      t.integer :jockey_owner_achievement_1
      t.integer :jockey_owner_achievement_2
      t.integer :jockey_owner_achievement_3
      t.integer :jockey_owner_achievement_4
      t.integer :jockey_blinker_achievement_1
      t.integer :jockey_blinker_achievement_2
      t.integer :jockey_blinker_achievement_3
      t.integer :jockey_blinker_achievement_4
      t.integer :trainer_owner_achievement_1
      t.integer :trainer_owner_achievement_2
      t.integer :trainer_owner_achievement_3
      t.integer :trainer_owner_achievement_4
      t.integer :turf_father_lineage_quinella_rate
      t.integer :dirt_father_lineage_quinella_rate
      t.string :father_lineage_quinella_rate_distance_avg
      t.integer :turf_maternal_father_lineage_quinella_rate
      t.integer :dirt_maternal_father_lineage_quinella_rate
      t.string :maternal_father_lineage_quinella_rate_distance_avg

      t.timestamps
    end
  end
end
