class CreateRaceHorses < ActiveRecord::Migration[5.1]
  def change
    create_table :race_horses do |t|

      t.string :race_key_course_code
      t.string :race_key_year
      t.string :race_key_times
      t.string :race_key_day
      t.string :race_key_number_of_race
      t.string :race_horse_number
      t.string :horse_pedigree_registration_code
      t.string :horse_name
      t.float :idm
      t.float :jockey_index
      t.float :infomation_index
      t.float :reserve_one
      t.float :reserve_two
      t.float :reseve_three
      t.float :composite_index
      t.string :leg_quality
      t.string :distance_aptitude
      t.string :rising_degree
      t.string :rotation
      t.float :standard_odds
      t.integer :standard_popularity_rank
      t.float :standard_show_odds
      t.integer :standard_show_popularity_rank
      t.integer :specific_info_excellent
      t.integer :specific_info_good
      t.integer :specific_info_fair
      t.integer :specific_info_bad
      t.integer :specific_info_failure
      t.integer :composite_info_excellent
      t.integer :composite_info_good
      t.integer :composite_info_fair
      t.integer :composite_info_bad
      t.integer :composite_info_failure
      t.integer :popularity_index
      t.float :training_index
      t.float :racing_stable_index
      t.string :training_arrow_code
      t.string :racing_stable_evaluation_code
      t.float :jockey_expected_confidence_rate
      t.float :rushing_index
      t.string :hoof_code
      t.string :heaviness_aptitude_code
      t.string :class_code
      t.string :reserve_four
      t.string :blinker_code
      t.string :jockey_name
      t.string :burden_weight
      t.string :apprentice_class
      t.string :trainer_name
      t.string :trainer_belong
      t.string :other_data_link_key_prebious_run_1_race_score_key
      t.string :other_data_link_key_prebious_run_2_race_score_key
      t.string :other_data_link_key_prebious_run_3_race_score_key
      t.string :other_data_link_key_prebious_run_4_race_score_key
      t.string :other_data_link_key_prebious_run_5_race_score_key
      t.string :other_data_link_key_prebious_run_1_race_key
      t.string :other_data_link_key_prebious_run_2_race_key
      t.string :other_data_link_key_prebious_run_3_race_key
      t.string :other_data_link_key_prebious_run_4_race_key
      t.string :other_data_link_key_prebious_run_5_race_key
      t.integer :bracket_number
      t.string :reserve_five
      t.string :mark_code_composite
      t.string :mark_code_idm
      t.string :mark_code_infomation
      t.string :mark_code_jockey
      t.string :mark_code_racing_stable
      t.string :mark_code_trainer
      t.string :mark_code_rushing
      t.string :turf_aptitude_code
      t.string :dirt_aptitude_code
      t.string :jockey_code
      t.string :trainer_code
      t.string :reserve_six
      t.integer :winning_prize
      t.integer :income_prize
      t.string :condition_class
      t.float :expansion_forecast_data_ten_index
      t.float :expansion_forecast_data_pace_index
      t.float :expansion_forecast_data_ricing_index
      t.float :expansion_forecast_data_position_index
      t.string :expansion_forecast_data_pace
      t.integer :expansion_forecast_data_halfway_ranking
      t.integer :expansion_forecast_data_halfway_difference
      t.string :expansion_forecast_data_halfway_Inside_outside
      t.integer :expansion_forecast_data_after_3f_time
      t.integer :expansion_forecast_data_after_3f_difference
      t.string :expansion_forecast_data_after_3f_Inside_outside
      t.integer :expansion_forecast_data_goal_ranking
      t.integer :expansion_forecast_data_goal_difference
      t.string :expansion_forecast_data_goal_Inside_outside
      t.string :expansion_forecast_data_expansion_symbol
      t.string :distance_aptitude_two
      t.string :horse_weight_fixed
      t.string :horse_weight_gain_fixed
      t.string :cancel_flg
      t.string :gender_code
      t.string :owner_name
      t.string :owner_belong_code
      t.string :horse_symbol_code
      t.integer :rushing_runking
      t.integer :ls_index_runking
      t.integer :ten_index_runking
      t.integer :pace_index_runking
      t.integer :rising_index_runking
      t.integer :position_index_runking
      t.float :jockey_expectation_victory_rate
      t.float :jockey_expectation_3_inside_rate
      t.string :transportation_class
      t.string :exercise
      t.string :body_type
      t.string :total_body_type_one
      t.string :total_body_type_two
      t.string :total_body_type_three
      t.string :horse_special_mention_one
      t.string :horse_special_mention_two
      t.string :horse_special_mention_three
      t.float :horse_start_index
      t.float :horse_departure_rate
      t.string :running_before_reference
      t.string :reference_riding_jockey_code
      t.integer :ten_thousand_ticket_index
      t.integer :ten_thousand_ticket_mark
      t.string :down_class_flg
      t.string :rushing_type
      t.string :recreation_reason_code
      t.string :flg
      t.string :racing_stable_running_times
      t.string :racing_stable_ymd
      t.string :racing_stable_days
      t.string :grazing_destination
      t.string :grazing_destination_rank
      t.string :racing_stable_rank

      t.timestamps
    end
  end
end
