class RegisteredHorseDatas < ActiveRecord::Migration[5.1]
  def change
    create_table :registered_horse_datas do |t|
      t.sting :race_key_course_code
      t.sting :race_key_year
      t.sting :race_key_times
      t.sting :race_key_day
      t.sting :race_key_number_of_race
      t.sting :horse_name_key
      t.sting :pedigree_registration_number
      t.sting :horse_name
      t.sting :gender_code
      t.sting :horse_symbol_code
      t.sting :brinker
      t.sting :jockey_name
      t.sting :burden_weight
      t.sting :apprentice_division
      t.sting :trainer_name
      t.sting :trainer_affiliation
      t.float :idm
      t.sting :the_degree_of_increase
      t.integer :rotation
      t.sting :ashishitsu
      t.sting :distance_suitability
      t.sting :distance_aptitude_2
      t.sting :turf_aptitude_code
      t.sting :da_aptitude_code
      t.sting :heavy_aptitude_code
      t.sting :hoof_code
      t.sting :class_code
      t.sting :hair_color_code
      t.sting :before_run_1_race_results_key
      t.sting :before_run_2_race_results_key
      t.sting :before_run_3_race_results_key
      t.sting :before_run_4_race_results_key
      t.sting :before_run_5_race_results_key
      t.sting :before_run_1_race_key
      t.sting :before_run_two_races_key
      t.sting :before_run_three_races_key
      t.sting :before_run_four_races_key
      t.sting :before_run_five_races_key
      t.sting :jockey_code
      t.sting :trainer_code
      t.integer :winnings
      t.integer :shutoku_prize
      t.sting :conditions_class
      t.sting :hashiho
      t.sting :figure
      t.sting :integrated_comprehensive_1
      t.sting :body_type_second_overall
      t.sting :body_type_third_overall
      t.sting :horse_special_1
      t.sting :horse_special_2
      t.sting :horse_otherwise_specified_3
      t.float :ten_index
      t.float :pace_index
      t.float :increase_index
      t.float :position_index
      t.float :horse_start_index
      t.float :maidashi_osoritsu
      t.sting :run_before_reference
      t.sting :jockey_code_run_before_reference
      t.sting :data_partition
      t.sting :race_ranking
      t.sting :reserve
      t.sting :new_line
    end
  end
end
