class CreateStandardQuinellaPlaceOdds < ActiveRecord::Migration[5.1]
  def change
    create_table :standard_quinella_place_odds do |t|
      t.string :race_key_course_code
      t.string :race_key_year
      t.string :race_key_times
      t.string :race_key_day
      t.string :race_key_number_of_race
      t.integer :registered_number
      t.float :quinella_place_odds1
      t.float :quinella_place_odds2
      t.float :quinella_place_odds3
      t.float :quinella_place_odds4
      t.float :quinella_place_odds5
      t.float :quinella_place_odds6
      t.float :quinella_place_odds7
      t.float :quinella_place_odds8
      t.float :quinella_place_odds9
      t.float :quinella_place_odds10
      t.float :quinella_place_odds11
      t.float :quinella_place_odds12
      t.float :quinella_place_odds13
      t.float :quinella_place_odds14
      t.float :quinella_place_odds15
      t.float :quinella_place_odds16
      t.float :quinella_place_odds17
      t.float :quinella_place_odds18
      t.float :quinella_place_odds19
      t.float :quinella_place_odds20
      t.float :quinella_place_odds21
      t.float :quinella_place_odds22
      t.float :quinella_place_odds23
      t.float :quinella_place_odds24
      t.float :quinella_place_odds25
      t.float :quinella_place_odds26
      t.float :quinella_place_odds27
      t.float :quinella_place_odds28
      t.float :quinella_place_odds29
      t.float :quinella_place_odds30
      t.float :quinella_place_odds31
      t.float :quinella_place_odds32
      t.float :quinella_place_odds33
      t.float :quinella_place_odds34
      t.float :quinella_place_odds35
      t.float :quinella_place_odds36
      t.float :quinella_place_odds37
      t.float :quinella_place_odds38
      t.float :quinella_place_odds39
      t.float :quinella_place_odds40
      t.float :quinella_place_odds41
      t.float :quinella_place_odds42
      t.float :quinella_place_odds43
      t.float :quinella_place_odds44
      t.float :quinella_place_odds45
      t.float :quinella_place_odds46
      t.float :quinella_place_odds47
      t.float :quinella_place_odds48
      t.float :quinella_place_odds49
      t.float :quinella_place_odds50
      t.float :quinella_place_odds51
      t.float :quinella_place_odds52
      t.float :quinella_place_odds53
      t.float :quinella_place_odds54
      t.float :quinella_place_odds55
      t.float :quinella_place_odds56
      t.float :quinella_place_odds57
      t.float :quinella_place_odds58
      t.float :quinella_place_odds59
      t.float :quinella_place_odds60
      t.float :quinella_place_odds61
      t.float :quinella_place_odds62
      t.float :quinella_place_odds63
      t.float :quinella_place_odds64
      t.float :quinella_place_odds65
      t.float :quinella_place_odds66
      t.float :quinella_place_odds67
      t.float :quinella_place_odds68
      t.float :quinella_place_odds69
      t.float :quinella_place_odds70
      t.float :quinella_place_odds71
      t.float :quinella_place_odds72
      t.float :quinella_place_odds73
      t.float :quinella_place_odds74
      t.float :quinella_place_odds75
      t.float :quinella_place_odds76
      t.float :quinella_place_odds77
      t.float :quinella_place_odds78
      t.float :quinella_place_odds79
      t.float :quinella_place_odds80
      t.float :quinella_place_odds81
      t.float :quinella_place_odds82
      t.float :quinella_place_odds83
      t.float :quinella_place_odds84
      t.float :quinella_place_odds85
      t.float :quinella_place_odds86
      t.float :quinella_place_odds87
      t.float :quinella_place_odds88
      t.float :quinella_place_odds89
      t.float :quinella_place_odds90
      t.float :quinella_place_odds91
      t.float :quinella_place_odds92
      t.float :quinella_place_odds93
      t.float :quinella_place_odds94
      t.float :quinella_place_odds95
      t.float :quinella_place_odds96
      t.float :quinella_place_odds97
      t.float :quinella_place_odds98
      t.float :quinella_place_odds99
      t.float :quinella_place_odds100
      t.float :quinella_place_odds101
      t.float :quinella_place_odds102
      t.float :quinella_place_odds103
      t.float :quinella_place_odds104
      t.float :quinella_place_odds105
      t.float :quinella_place_odds106
      t.float :quinella_place_odds107
      t.float :quinella_place_odds108
      t.float :quinella_place_odds109
      t.float :quinella_place_odds110
      t.float :quinella_place_odds111
      t.float :quinella_place_odds112
      t.float :quinella_place_odds113
      t.float :quinella_place_odds114
      t.float :quinella_place_odds115
      t.float :quinella_place_odds116
      t.float :quinella_place_odds117
      t.float :quinella_place_odds118
      t.float :quinella_place_odds119
      t.float :quinella_place_odds120
      t.float :quinella_place_odds121
      t.float :quinella_place_odds122
      t.float :quinella_place_odds123
      t.float :quinella_place_odds124
      t.float :quinella_place_odds125
      t.float :quinella_place_odds126
      t.float :quinella_place_odds127
      t.float :quinella_place_odds128
      t.float :quinella_place_odds129
      t.float :quinella_place_odds130
      t.float :quinella_place_odds131
      t.float :quinella_place_odds132
      t.float :quinella_place_odds133
      t.float :quinella_place_odds134
      t.float :quinella_place_odds135
      t.float :quinella_place_odds136
      t.float :quinella_place_odds137
      t.float :quinella_place_odds138
      t.float :quinella_place_odds139
      t.float :quinella_place_odds140
      t.float :quinella_place_odds141
      t.float :quinella_place_odds142
      t.float :quinella_place_odds143
      t.float :quinella_place_odds144
      t.float :quinella_place_odds145
      t.float :quinella_place_odds146
      t.float :quinella_place_odds147
      t.float :quinella_place_odds148
      t.float :quinella_place_odds149
      t.float :quinella_place_odds150
      t.float :quinella_place_odds151
      t.float :quinella_place_odds152
      t.float :quinella_place_odds153

      t.timestamps
    end
  end
end
