class RefundInformationDatas < ActiveRecord::Migration[5.1]
  def change
    create_table :refund_information_datas do |t|
      t.string :race_key_course_code
      t.string :race_key_year
      t.string :race_key_times
      t.string :race_key_day
      t.string :race_key_number_of_race
      t.string :win_horse_number_1
      t.integer :win_refund_1
      t.string :win_horse_number_2
      t.integer :win_refund_2
      t.string :win_horse_number_3
      t.integer :win_refund_3
      t.string :multiple_wins_refund_horse_number_1
      t.integer :multiple_wins_refund_1
      t.string :multiple_wins_reimbursement_horse_number_2
      t.integer :multiple_wins_refund_2
      t.string :multiple_wins_reimbursement_horse_number_3
      t.integer :multiple_wins_refund_3
      t.string :multiple_wins_reimbursement_horse_number_4
      t.integer :double_wins_refund_4
      t.string :multiple_wins_reimbursement_horse_number_5
      t.integer :multiple_wins_refund_5
      t.string :wakuren_frame_program_combined_1
      t.integer :wakuren_refund_refund_1
      t.string :wakuren_frame_program_together_2
      t.integer :wakuren_reimbursement_refund_2
      t.string :wakuren_frame_program_combined_3
      t.integer :wakuren_reimbursement_refund_3
      t.string :valentin_horse_number_combination_1
      t.integer :valentin_refund_1
      t.string :valentin_horse_number_combination_2
      t.integer :valentin_refund_2
      t.string :valentin_horse_number_combination_3
      t.integer :valentin_refund_3
      t.string :wide_horse_number_combination_1
      t.integer :wide_withdrawal_1
      t.string :wide_horse_number_combination_2
      t.integer :wide_reimbursement_2
      t.string :wide_horse_number_combination_3
      t.integer :wide_reimbursement_3
      t.string :wide_horse_number_combination_4
      t.integer :wide_refund_4
      t.string :wide_horse_number_combination_5
      t.integer :wide_refund_5
      t.string :wide_horse_number_combination_6
      t.integer :wide_reimbursement_6
      t.string :wide_horse_number_combination_7
      t.integer :wide_reimbursement_7
      t.string :horse_single_horse_number_combination_1
      t.integer :horse_single_reimbursement_1
      t.string :horse_single_horse_number_combination_2
      t.integer :horse_single_reimbursement_2
      t.string :horse_single_horse_number_combination_3
      t.integer :horse_single_reimbursement_3
      t.string :horse_single_horse_number_combination_4
      t.integer :horse_single_reimbursement_4
      t.string :horse_single_horse_number_combination_5
      t.integer :horse_single_reimbursement_5
      t.string :horse_single_horse_number_combination_6
      t.integer :horse_single_reimbursement_6
      t.string :triple_double_horse_number_combination_1
      t.integer :triple_double_withdrawal_1
      t.string :triple_double_horse_number_combination_2
      t.integer :triple_double_reimbursement_2
      t.string :triple_double_horse_number_combination_3
      t.integer :triple_double_reimbursement_3
      t.string :trifecta_horse_number_combination_1
      t.integer :trifecta_withdrawal_1
      t.string :trifecta_horse_number_combination_2
      t.integer :trifecta_reimbursement_2
      t.string :trifecta_horse_number_combination_3
      t.integer :trifecta_reimbursement_3
      t.string :trifecta_horse_number_combination_4
      t.integer :trifecta_refund_4
      t.string :trifecta_horse_number_combination_5
      t.integer :trifecta_refund_5
      t.string :trifecta_horse_number_combination_6
      t.integer :trifecta_reimbursement_6
      t.string :preliminary_1
      t.string :and_2
    end
  end
end
