class CreateStandardStandardExactaOdds < ActiveRecord::Migration[5.1]
  def change
    create_table :standard_standard_exacta_odds do |t|

      t.string :race_key_course_code
      t.string :race_key_year
      t.string :race_key_times
      t.string :race_key_day
      t.string :race_key_number_of_race
      t.integer :registered_number
      t.float :standard_exacta_odds1
      t.float :standard_exacta_odds2
      t.float :standard_exacta_odds3
      t.float :standard_exacta_odds4
      t.float :standard_exacta_odds5
      t.float :standard_exacta_odds6
      t.float :standard_exacta_odds7
      t.float :standard_exacta_odds8
      t.float :standard_exacta_odds9
      t.float :standard_exacta_odds10
      t.float :standard_exacta_odds11
      t.float :standard_exacta_odds12
      t.float :standard_exacta_odds13
      t.float :standard_exacta_odds14
      t.float :standard_exacta_odds15
      t.float :standard_exacta_odds16
      t.float :standard_exacta_odds17
      t.float :standard_exacta_odds18
      t.float :standard_exacta_odds19
      t.float :standard_exacta_odds20
      t.float :standard_exacta_odds21
      t.float :standard_exacta_odds22
      t.float :standard_exacta_odds23
      t.float :standard_exacta_odds24
      t.float :standard_exacta_odds25
      t.float :standard_exacta_odds26
      t.float :standard_exacta_odds27
      t.float :standard_exacta_odds28
      t.float :standard_exacta_odds29
      t.float :standard_exacta_odds30
      t.float :standard_exacta_odds31
      t.float :standard_exacta_odds32
      t.float :standard_exacta_odds33
      t.float :standard_exacta_odds34
      t.float :standard_exacta_odds35
      t.float :standard_exacta_odds36
      t.float :standard_exacta_odds37
      t.float :standard_exacta_odds38
      t.float :standard_exacta_odds39
      t.float :standard_exacta_odds40
      t.float :standard_exacta_odds41
      t.float :standard_exacta_odds42
      t.float :standard_exacta_odds43
      t.float :standard_exacta_odds44
      t.float :standard_exacta_odds45
      t.float :standard_exacta_odds46
      t.float :standard_exacta_odds47
      t.float :standard_exacta_odds48
      t.float :standard_exacta_odds49
      t.float :standard_exacta_odds50
      t.float :standard_exacta_odds51
      t.float :standard_exacta_odds52
      t.float :standard_exacta_odds53
      t.float :standard_exacta_odds54
      t.float :standard_exacta_odds55
      t.float :standard_exacta_odds56
      t.float :standard_exacta_odds57
      t.float :standard_exacta_odds58
      t.float :standard_exacta_odds59
      t.float :standard_exacta_odds60
      t.float :standard_exacta_odds61
      t.float :standard_exacta_odds62
      t.float :standard_exacta_odds63
      t.float :standard_exacta_odds64
      t.float :standard_exacta_odds65
      t.float :standard_exacta_odds66
      t.float :standard_exacta_odds67
      t.float :standard_exacta_odds68
      t.float :standard_exacta_odds69
      t.float :standard_exacta_odds70
      t.float :standard_exacta_odds71
      t.float :standard_exacta_odds72
      t.float :standard_exacta_odds73
      t.float :standard_exacta_odds74
      t.float :standard_exacta_odds75
      t.float :standard_exacta_odds76
      t.float :standard_exacta_odds77
      t.float :standard_exacta_odds78
      t.float :standard_exacta_odds79
      t.float :standard_exacta_odds80
      t.float :standard_exacta_odds81
      t.float :standard_exacta_odds82
      t.float :standard_exacta_odds83
      t.float :standard_exacta_odds84
      t.float :standard_exacta_odds85
      t.float :standard_exacta_odds86
      t.float :standard_exacta_odds87
      t.float :standard_exacta_odds88
      t.float :standard_exacta_odds89
      t.float :standard_exacta_odds90
      t.float :standard_exacta_odds91
      t.float :standard_exacta_odds92
      t.float :standard_exacta_odds93
      t.float :standard_exacta_odds94
      t.float :standard_exacta_odds95
      t.float :standard_exacta_odds96
      t.float :standard_exacta_odds97
      t.float :standard_exacta_odds98
      t.float :standard_exacta_odds99
      t.float :standard_exacta_odds100
      t.float :standard_exacta_odds101
      t.float :standard_exacta_odds102
      t.float :standard_exacta_odds103
      t.float :standard_exacta_odds104
      t.float :standard_exacta_odds105
      t.float :standard_exacta_odds106
      t.float :standard_exacta_odds107
      t.float :standard_exacta_odds108
      t.float :standard_exacta_odds109
      t.float :standard_exacta_odds110
      t.float :standard_exacta_odds111
      t.float :standard_exacta_odds112
      t.float :standard_exacta_odds113
      t.float :standard_exacta_odds114
      t.float :standard_exacta_odds115
      t.float :standard_exacta_odds116
      t.float :standard_exacta_odds117
      t.float :standard_exacta_odds118
      t.float :standard_exacta_odds119
      t.float :standard_exacta_odds120
      t.float :standard_exacta_odds121
      t.float :standard_exacta_odds122
      t.float :standard_exacta_odds123
      t.float :standard_exacta_odds124
      t.float :standard_exacta_odds125
      t.float :standard_exacta_odds126
      t.float :standard_exacta_odds127
      t.float :standard_exacta_odds128
      t.float :standard_exacta_odds129
      t.float :standard_exacta_odds130
      t.float :standard_exacta_odds131
      t.float :standard_exacta_odds132
      t.float :standard_exacta_odds133
      t.float :standard_exacta_odds134
      t.float :standard_exacta_odds135
      t.float :standard_exacta_odds136
      t.float :standard_exacta_odds137
      t.float :standard_exacta_odds138
      t.float :standard_exacta_odds139
      t.float :standard_exacta_odds140
      t.float :standard_exacta_odds141
      t.float :standard_exacta_odds142
      t.float :standard_exacta_odds143
      t.float :standard_exacta_odds144
      t.float :standard_exacta_odds145
      t.float :standard_exacta_odds146
      t.float :standard_exacta_odds147
      t.float :standard_exacta_odds148
      t.float :standard_exacta_odds149
      t.float :standard_exacta_odds150
      t.float :standard_exacta_odds151
      t.float :standard_exacta_odds152
      t.float :standard_exacta_odds153

      t.timestamps
    end
  end
end
