class CreateStandardTrioOdds < ActiveRecord::Migration[5.1]
  def change
    create_table :standard_trio_odds do |t|

      t.string :race_key_course_code
      t.string :race_key_year
      t.string :race_key_times
      t.string :race_key_day
      t.string :race_key_number_of_race
      t.integer :registered_number
      t.float :standard_trio_odds1
      t.float :standard_trio_odds2
      t.float :standard_trio_odds3
      t.float :standard_trio_odds4
      t.float :standard_trio_odds5
      t.float :standard_trio_odds6
      t.float :standard_trio_odds7
      t.float :standard_trio_odds8
      t.float :standard_trio_odds9
      t.float :standard_trio_odds10
      t.float :standard_trio_odds11
      t.float :standard_trio_odds12
      t.float :standard_trio_odds13
      t.float :standard_trio_odds14
      t.float :standard_trio_odds15
      t.float :standard_trio_odds16
      t.float :standard_trio_odds17
      t.float :standard_trio_odds18
      t.float :standard_trio_odds19
      t.float :standard_trio_odds20
      t.float :standard_trio_odds21
      t.float :standard_trio_odds22
      t.float :standard_trio_odds23
      t.float :standard_trio_odds24
      t.float :standard_trio_odds25
      t.float :standard_trio_odds26
      t.float :standard_trio_odds27
      t.float :standard_trio_odds28
      t.float :standard_trio_odds29
      t.float :standard_trio_odds30
      t.float :standard_trio_odds31
      t.float :standard_trio_odds32
      t.float :standard_trio_odds33
      t.float :standard_trio_odds34
      t.float :standard_trio_odds35
      t.float :standard_trio_odds36
      t.float :standard_trio_odds37
      t.float :standard_trio_odds38
      t.float :standard_trio_odds39
      t.float :standard_trio_odds40
      t.float :standard_trio_odds41
      t.float :standard_trio_odds42
      t.float :standard_trio_odds43
      t.float :standard_trio_odds44
      t.float :standard_trio_odds45
      t.float :standard_trio_odds46
      t.float :standard_trio_odds47
      t.float :standard_trio_odds48
      t.float :standard_trio_odds49
      t.float :standard_trio_odds50
      t.float :standard_trio_odds51
      t.float :standard_trio_odds52
      t.float :standard_trio_odds53
      t.float :standard_trio_odds54
      t.float :standard_trio_odds55
      t.float :standard_trio_odds56
      t.float :standard_trio_odds57
      t.float :standard_trio_odds58
      t.float :standard_trio_odds59
      t.float :standard_trio_odds60
      t.float :standard_trio_odds61
      t.float :standard_trio_odds62
      t.float :standard_trio_odds63
      t.float :standard_trio_odds64
      t.float :standard_trio_odds65
      t.float :standard_trio_odds66
      t.float :standard_trio_odds67
      t.float :standard_trio_odds68
      t.float :standard_trio_odds69
      t.float :standard_trio_odds70
      t.float :standard_trio_odds71
      t.float :standard_trio_odds72
      t.float :standard_trio_odds73
      t.float :standard_trio_odds74
      t.float :standard_trio_odds75
      t.float :standard_trio_odds76
      t.float :standard_trio_odds77
      t.float :standard_trio_odds78
      t.float :standard_trio_odds79
      t.float :standard_trio_odds80
      t.float :standard_trio_odds81
      t.float :standard_trio_odds82
      t.float :standard_trio_odds83
      t.float :standard_trio_odds84
      t.float :standard_trio_odds85
      t.float :standard_trio_odds86
      t.float :standard_trio_odds87
      t.float :standard_trio_odds88
      t.float :standard_trio_odds89
      t.float :standard_trio_odds90
      t.float :standard_trio_odds91
      t.float :standard_trio_odds92
      t.float :standard_trio_odds93
      t.float :standard_trio_odds94
      t.float :standard_trio_odds95
      t.float :standard_trio_odds96
      t.float :standard_trio_odds97
      t.float :standard_trio_odds98
      t.float :standard_trio_odds99
      t.float :standard_trio_odds100
      t.float :standard_trio_odds101
      t.float :standard_trio_odds102
      t.float :standard_trio_odds103
      t.float :standard_trio_odds104
      t.float :standard_trio_odds105
      t.float :standard_trio_odds106
      t.float :standard_trio_odds107
      t.float :standard_trio_odds108
      t.float :standard_trio_odds109
      t.float :standard_trio_odds110
      t.float :standard_trio_odds111
      t.float :standard_trio_odds112
      t.float :standard_trio_odds113
      t.float :standard_trio_odds114
      t.float :standard_trio_odds115
      t.float :standard_trio_odds116
      t.float :standard_trio_odds117
      t.float :standard_trio_odds118
      t.float :standard_trio_odds119
      t.float :standard_trio_odds120
      t.float :standard_trio_odds121
      t.float :standard_trio_odds122
      t.float :standard_trio_odds123
      t.float :standard_trio_odds124
      t.float :standard_trio_odds125
      t.float :standard_trio_odds126
      t.float :standard_trio_odds127
      t.float :standard_trio_odds128
      t.float :standard_trio_odds129
      t.float :standard_trio_odds130
      t.float :standard_trio_odds131
      t.float :standard_trio_odds132
      t.float :standard_trio_odds133
      t.float :standard_trio_odds134
      t.float :standard_trio_odds135
      t.float :standard_trio_odds136
      t.float :standard_trio_odds137
      t.float :standard_trio_odds138
      t.float :standard_trio_odds139
      t.float :standard_trio_odds140
      t.float :standard_trio_odds141
      t.float :standard_trio_odds142
      t.float :standard_trio_odds143
      t.float :standard_trio_odds144
      t.float :standard_trio_odds145
      t.float :standard_trio_odds146
      t.float :standard_trio_odds147
      t.float :standard_trio_odds148
      t.float :standard_trio_odds149
      t.float :standard_trio_odds150
      t.float :standard_trio_odds151
      t.float :standard_trio_odds152
      t.float :standard_trio_odds153
      t.float :standard_trio_odds154
      t.float :standard_trio_odds155
      t.float :standard_trio_odds156
      t.float :standard_trio_odds157
      t.float :standard_trio_odds158
      t.float :standard_trio_odds159
      t.float :standard_trio_odds160
      t.float :standard_trio_odds161
      t.float :standard_trio_odds162
      t.float :standard_trio_odds163
      t.float :standard_trio_odds164
      t.float :standard_trio_odds165
      t.float :standard_trio_odds166
      t.float :standard_trio_odds167
      t.float :standard_trio_odds168
      t.float :standard_trio_odds169
      t.float :standard_trio_odds170
      t.float :standard_trio_odds171
      t.float :standard_trio_odds172
      t.float :standard_trio_odds173
      t.float :standard_trio_odds174
      t.float :standard_trio_odds175
      t.float :standard_trio_odds176
      t.float :standard_trio_odds177
      t.float :standard_trio_odds178
      t.float :standard_trio_odds179
      t.float :standard_trio_odds180
      t.float :standard_trio_odds181
      t.float :standard_trio_odds182
      t.float :standard_trio_odds183
      t.float :standard_trio_odds184
      t.float :standard_trio_odds185
      t.float :standard_trio_odds186
      t.float :standard_trio_odds187
      t.float :standard_trio_odds188
      t.float :standard_trio_odds189
      t.float :standard_trio_odds190
      t.float :standard_trio_odds191
      t.float :standard_trio_odds192
      t.float :standard_trio_odds193
      t.float :standard_trio_odds194
      t.float :standard_trio_odds195
      t.float :standard_trio_odds196
      t.float :standard_trio_odds197
      t.float :standard_trio_odds198
      t.float :standard_trio_odds199
      t.float :standard_trio_odds200
      t.float :standard_trio_odds201
      t.float :standard_trio_odds202
      t.float :standard_trio_odds203
      t.float :standard_trio_odds204
      t.float :standard_trio_odds205
      t.float :standard_trio_odds206
      t.float :standard_trio_odds207
      t.float :standard_trio_odds208
      t.float :standard_trio_odds209
      t.float :standard_trio_odds210
      t.float :standard_trio_odds211
      t.float :standard_trio_odds212
      t.float :standard_trio_odds213
      t.float :standard_trio_odds214
      t.float :standard_trio_odds215
      t.float :standard_trio_odds216
      t.float :standard_trio_odds217
      t.float :standard_trio_odds218
      t.float :standard_trio_odds219
      t.float :standard_trio_odds220
      t.float :standard_trio_odds221
      t.float :standard_trio_odds222
      t.float :standard_trio_odds223
      t.float :standard_trio_odds224
      t.float :standard_trio_odds225
      t.float :standard_trio_odds226
      t.float :standard_trio_odds227
      t.float :standard_trio_odds228
      t.float :standard_trio_odds229
      t.float :standard_trio_odds230
      t.float :standard_trio_odds231
      t.float :standard_trio_odds232
      t.float :standard_trio_odds233
      t.float :standard_trio_odds234
      t.float :standard_trio_odds235
      t.float :standard_trio_odds236
      t.float :standard_trio_odds237
      t.float :standard_trio_odds238
      t.float :standard_trio_odds239
      t.float :standard_trio_odds240
      t.float :standard_trio_odds241
      t.float :standard_trio_odds242
      t.float :standard_trio_odds243
      t.float :standard_trio_odds244
      t.float :standard_trio_odds245
      t.float :standard_trio_odds246
      t.float :standard_trio_odds247
      t.float :standard_trio_odds248
      t.float :standard_trio_odds249
      t.float :standard_trio_odds250
      t.float :standard_trio_odds251
      t.float :standard_trio_odds252
      t.float :standard_trio_odds253
      t.float :standard_trio_odds254
      t.float :standard_trio_odds255
      t.float :standard_trio_odds256
      t.float :standard_trio_odds257
      t.float :standard_trio_odds258
      t.float :standard_trio_odds259
      t.float :standard_trio_odds260
      t.float :standard_trio_odds261
      t.float :standard_trio_odds262
      t.float :standard_trio_odds263
      t.float :standard_trio_odds264
      t.float :standard_trio_odds265
      t.float :standard_trio_odds266
      t.float :standard_trio_odds267
      t.float :standard_trio_odds268
      t.float :standard_trio_odds269
      t.float :standard_trio_odds270
      t.float :standard_trio_odds271
      t.float :standard_trio_odds272
      t.float :standard_trio_odds273
      t.float :standard_trio_odds274
      t.float :standard_trio_odds275
      t.float :standard_trio_odds276
      t.float :standard_trio_odds277
      t.float :standard_trio_odds278
      t.float :standard_trio_odds279
      t.float :standard_trio_odds280
      t.float :standard_trio_odds281
      t.float :standard_trio_odds282
      t.float :standard_trio_odds283
      t.float :standard_trio_odds284
      t.float :standard_trio_odds285
      t.float :standard_trio_odds286
      t.float :standard_trio_odds287
      t.float :standard_trio_odds288
      t.float :standard_trio_odds289
      t.float :standard_trio_odds290
      t.float :standard_trio_odds291
      t.float :standard_trio_odds292
      t.float :standard_trio_odds293
      t.float :standard_trio_odds294
      t.float :standard_trio_odds295
      t.float :standard_trio_odds296
      t.float :standard_trio_odds297
      t.float :standard_trio_odds298
      t.float :standard_trio_odds299
      t.float :standard_trio_odds300
      t.float :standard_trio_odds301
      t.float :standard_trio_odds302
      t.float :standard_trio_odds303
      t.float :standard_trio_odds304
      t.float :standard_trio_odds305
      t.float :standard_trio_odds306
      t.float :standard_trio_odds307
      t.float :standard_trio_odds308
      t.float :standard_trio_odds309
      t.float :standard_trio_odds310
      t.float :standard_trio_odds311
      t.float :standard_trio_odds312
      t.float :standard_trio_odds313
      t.float :standard_trio_odds314
      t.float :standard_trio_odds315
      t.float :standard_trio_odds316
      t.float :standard_trio_odds317
      t.float :standard_trio_odds318
      t.float :standard_trio_odds319
      t.float :standard_trio_odds320
      t.float :standard_trio_odds321
      t.float :standard_trio_odds322
      t.float :standard_trio_odds323
      t.float :standard_trio_odds324
      t.float :standard_trio_odds325
      t.float :standard_trio_odds326
      t.float :standard_trio_odds327
      t.float :standard_trio_odds328
      t.float :standard_trio_odds329
      t.float :standard_trio_odds330
      t.float :standard_trio_odds331
      t.float :standard_trio_odds332
      t.float :standard_trio_odds333
      t.float :standard_trio_odds334
      t.float :standard_trio_odds335
      t.float :standard_trio_odds336
      t.float :standard_trio_odds337
      t.float :standard_trio_odds338
      t.float :standard_trio_odds339
      t.float :standard_trio_odds340
      t.float :standard_trio_odds341
      t.float :standard_trio_odds342
      t.float :standard_trio_odds343
      t.float :standard_trio_odds344
      t.float :standard_trio_odds345
      t.float :standard_trio_odds346
      t.float :standard_trio_odds347
      t.float :standard_trio_odds348
      t.float :standard_trio_odds349
      t.float :standard_trio_odds350
      t.float :standard_trio_odds351
      t.float :standard_trio_odds352
      t.float :standard_trio_odds353
      t.float :standard_trio_odds354
      t.float :standard_trio_odds355
      t.float :standard_trio_odds356
      t.float :standard_trio_odds357
      t.float :standard_trio_odds358
      t.float :standard_trio_odds359
      t.float :standard_trio_odds360
      t.float :standard_trio_odds361
      t.float :standard_trio_odds362
      t.float :standard_trio_odds363
      t.float :standard_trio_odds364
      t.float :standard_trio_odds365
      t.float :standard_trio_odds366
      t.float :standard_trio_odds367
      t.float :standard_trio_odds368
      t.float :standard_trio_odds369
      t.float :standard_trio_odds370
      t.float :standard_trio_odds371
      t.float :standard_trio_odds372
      t.float :standard_trio_odds373
      t.float :standard_trio_odds374
      t.float :standard_trio_odds375
      t.float :standard_trio_odds376
      t.float :standard_trio_odds377
      t.float :standard_trio_odds378
      t.float :standard_trio_odds379
      t.float :standard_trio_odds380
      t.float :standard_trio_odds381
      t.float :standard_trio_odds382
      t.float :standard_trio_odds383
      t.float :standard_trio_odds384
      t.float :standard_trio_odds385
      t.float :standard_trio_odds386
      t.float :standard_trio_odds387
      t.float :standard_trio_odds388
      t.float :standard_trio_odds389
      t.float :standard_trio_odds390
      t.float :standard_trio_odds391
      t.float :standard_trio_odds392
      t.float :standard_trio_odds393
      t.float :standard_trio_odds394
      t.float :standard_trio_odds395
      t.float :standard_trio_odds396
      t.float :standard_trio_odds397
      t.float :standard_trio_odds398
      t.float :standard_trio_odds399
      t.float :standard_trio_odds400
      t.float :standard_trio_odds401
      t.float :standard_trio_odds402
      t.float :standard_trio_odds403
      t.float :standard_trio_odds404
      t.float :standard_trio_odds405
      t.float :standard_trio_odds406
      t.float :standard_trio_odds407
      t.float :standard_trio_odds408
      t.float :standard_trio_odds409
      t.float :standard_trio_odds410
      t.float :standard_trio_odds411
      t.float :standard_trio_odds412
      t.float :standard_trio_odds413
      t.float :standard_trio_odds414
      t.float :standard_trio_odds415
      t.float :standard_trio_odds416
      t.float :standard_trio_odds417
      t.float :standard_trio_odds418
      t.float :standard_trio_odds419
      t.float :standard_trio_odds420
      t.float :standard_trio_odds421
      t.float :standard_trio_odds422
      t.float :standard_trio_odds423
      t.float :standard_trio_odds424
      t.float :standard_trio_odds425
      t.float :standard_trio_odds426
      t.float :standard_trio_odds427
      t.float :standard_trio_odds428
      t.float :standard_trio_odds429
      t.float :standard_trio_odds430
      t.float :standard_trio_odds431
      t.float :standard_trio_odds432
      t.float :standard_trio_odds433
      t.float :standard_trio_odds434
      t.float :standard_trio_odds435
      t.float :standard_trio_odds436
      t.float :standard_trio_odds437
      t.float :standard_trio_odds438
      t.float :standard_trio_odds439
      t.float :standard_trio_odds440
      t.float :standard_trio_odds441
      t.float :standard_trio_odds442
      t.float :standard_trio_odds443
      t.float :standard_trio_odds444
      t.float :standard_trio_odds445
      t.float :standard_trio_odds446
      t.float :standard_trio_odds447
      t.float :standard_trio_odds448
      t.float :standard_trio_odds449
      t.float :standard_trio_odds450
      t.float :standard_trio_odds451
      t.float :standard_trio_odds452
      t.float :standard_trio_odds453
      t.float :standard_trio_odds454
      t.float :standard_trio_odds455
      t.float :standard_trio_odds456
      t.float :standard_trio_odds457
      t.float :standard_trio_odds458
      t.float :standard_trio_odds459
      t.float :standard_trio_odds460
      t.float :standard_trio_odds461
      t.float :standard_trio_odds462
      t.float :standard_trio_odds463
      t.float :standard_trio_odds464
      t.float :standard_trio_odds465
      t.float :standard_trio_odds466
      t.float :standard_trio_odds467
      t.float :standard_trio_odds468
      t.float :standard_trio_odds469
      t.float :standard_trio_odds470
      t.float :standard_trio_odds471
      t.float :standard_trio_odds472
      t.float :standard_trio_odds473
      t.float :standard_trio_odds474
      t.float :standard_trio_odds475
      t.float :standard_trio_odds476
      t.float :standard_trio_odds477
      t.float :standard_trio_odds478
      t.float :standard_trio_odds479
      t.float :standard_trio_odds480
      t.float :standard_trio_odds481
      t.float :standard_trio_odds482
      t.float :standard_trio_odds483
      t.float :standard_trio_odds484
      t.float :standard_trio_odds485
      t.float :standard_trio_odds486
      t.float :standard_trio_odds487
      t.float :standard_trio_odds488
      t.float :standard_trio_odds489
      t.float :standard_trio_odds490
      t.float :standard_trio_odds491
      t.float :standard_trio_odds492
      t.float :standard_trio_odds493
      t.float :standard_trio_odds494
      t.float :standard_trio_odds495
      t.float :standard_trio_odds496
      t.float :standard_trio_odds497
      t.float :standard_trio_odds498
      t.float :standard_trio_odds499
      t.float :standard_trio_odds500
      t.float :standard_trio_odds501
      t.float :standard_trio_odds502
      t.float :standard_trio_odds503
      t.float :standard_trio_odds504
      t.float :standard_trio_odds505
      t.float :standard_trio_odds506
      t.float :standard_trio_odds507
      t.float :standard_trio_odds508
      t.float :standard_trio_odds509
      t.float :standard_trio_odds510
      t.float :standard_trio_odds511
      t.float :standard_trio_odds512
      t.float :standard_trio_odds513
      t.float :standard_trio_odds514
      t.float :standard_trio_odds515
      t.float :standard_trio_odds516
      t.float :standard_trio_odds517
      t.float :standard_trio_odds518
      t.float :standard_trio_odds519
      t.float :standard_trio_odds520
      t.float :standard_trio_odds521
      t.float :standard_trio_odds522
      t.float :standard_trio_odds523
      t.float :standard_trio_odds524
      t.float :standard_trio_odds525
      t.float :standard_trio_odds526
      t.float :standard_trio_odds527
      t.float :standard_trio_odds528
      t.float :standard_trio_odds529
      t.float :standard_trio_odds530
      t.float :standard_trio_odds531
      t.float :standard_trio_odds532
      t.float :standard_trio_odds533
      t.float :standard_trio_odds534
      t.float :standard_trio_odds535
      t.float :standard_trio_odds536
      t.float :standard_trio_odds537
      t.float :standard_trio_odds538
      t.float :standard_trio_odds539
      t.float :standard_trio_odds540
      t.float :standard_trio_odds541
      t.float :standard_trio_odds542
      t.float :standard_trio_odds543
      t.float :standard_trio_odds544
      t.float :standard_trio_odds545
      t.float :standard_trio_odds546
      t.float :standard_trio_odds547
      t.float :standard_trio_odds548
      t.float :standard_trio_odds549
      t.float :standard_trio_odds550
      t.float :standard_trio_odds551
      t.float :standard_trio_odds552
      t.float :standard_trio_odds553
      t.float :standard_trio_odds554
      t.float :standard_trio_odds555
      t.float :standard_trio_odds556
      t.float :standard_trio_odds557
      t.float :standard_trio_odds558
      t.float :standard_trio_odds559
      t.float :standard_trio_odds560
      t.float :standard_trio_odds561
      t.float :standard_trio_odds562
      t.float :standard_trio_odds563
      t.float :standard_trio_odds564
      t.float :standard_trio_odds565
      t.float :standard_trio_odds566
      t.float :standard_trio_odds567
      t.float :standard_trio_odds568
      t.float :standard_trio_odds569
      t.float :standard_trio_odds570
      t.float :standard_trio_odds571
      t.float :standard_trio_odds572
      t.float :standard_trio_odds573
      t.float :standard_trio_odds574
      t.float :standard_trio_odds575
      t.float :standard_trio_odds576
      t.float :standard_trio_odds577
      t.float :standard_trio_odds578
      t.float :standard_trio_odds579
      t.float :standard_trio_odds580
      t.float :standard_trio_odds581
      t.float :standard_trio_odds582
      t.float :standard_trio_odds583
      t.float :standard_trio_odds584
      t.float :standard_trio_odds585
      t.float :standard_trio_odds586
      t.float :standard_trio_odds587
      t.float :standard_trio_odds588
      t.float :standard_trio_odds589
      t.float :standard_trio_odds590
      t.float :standard_trio_odds591
      t.float :standard_trio_odds592
      t.float :standard_trio_odds593
      t.float :standard_trio_odds594
      t.float :standard_trio_odds595
      t.float :standard_trio_odds596
      t.float :standard_trio_odds597
      t.float :standard_trio_odds598
      t.float :standard_trio_odds599
      t.float :standard_trio_odds600
      t.float :standard_trio_odds601
      t.float :standard_trio_odds602
      t.float :standard_trio_odds603
      t.float :standard_trio_odds604
      t.float :standard_trio_odds605
      t.float :standard_trio_odds606
      t.float :standard_trio_odds607
      t.float :standard_trio_odds608
      t.float :standard_trio_odds609
      t.float :standard_trio_odds610
      t.float :standard_trio_odds611
      t.float :standard_trio_odds612
      t.float :standard_trio_odds613
      t.float :standard_trio_odds614
      t.float :standard_trio_odds615
      t.float :standard_trio_odds616
      t.float :standard_trio_odds617
      t.float :standard_trio_odds618
      t.float :standard_trio_odds619
      t.float :standard_trio_odds620
      t.float :standard_trio_odds621
      t.float :standard_trio_odds622
      t.float :standard_trio_odds623
      t.float :standard_trio_odds624
      t.float :standard_trio_odds625
      t.float :standard_trio_odds626
      t.float :standard_trio_odds627
      t.float :standard_trio_odds628
      t.float :standard_trio_odds629
      t.float :standard_trio_odds630
      t.float :standard_trio_odds631
      t.float :standard_trio_odds632
      t.float :standard_trio_odds633
      t.float :standard_trio_odds634
      t.float :standard_trio_odds635
      t.float :standard_trio_odds636
      t.float :standard_trio_odds637
      t.float :standard_trio_odds638
      t.float :standard_trio_odds639
      t.float :standard_trio_odds640
      t.float :standard_trio_odds641
      t.float :standard_trio_odds642
      t.float :standard_trio_odds643
      t.float :standard_trio_odds644
      t.float :standard_trio_odds645
      t.float :standard_trio_odds646
      t.float :standard_trio_odds647
      t.float :standard_trio_odds648
      t.float :standard_trio_odds649
      t.float :standard_trio_odds650
      t.float :standard_trio_odds651
      t.float :standard_trio_odds652
      t.float :standard_trio_odds653
      t.float :standard_trio_odds654
      t.float :standard_trio_odds655
      t.float :standard_trio_odds656
      t.float :standard_trio_odds657
      t.float :standard_trio_odds658
      t.float :standard_trio_odds659
      t.float :standard_trio_odds660
      t.float :standard_trio_odds661
      t.float :standard_trio_odds662
      t.float :standard_trio_odds663
      t.float :standard_trio_odds664
      t.float :standard_trio_odds665
      t.float :standard_trio_odds666
      t.float :standard_trio_odds667
      t.float :standard_trio_odds668
      t.float :standard_trio_odds669
      t.float :standard_trio_odds670
      t.float :standard_trio_odds671
      t.float :standard_trio_odds672
      t.float :standard_trio_odds673
      t.float :standard_trio_odds674
      t.float :standard_trio_odds675
      t.float :standard_trio_odds676
      t.float :standard_trio_odds677
      t.float :standard_trio_odds678
      t.float :standard_trio_odds679
      t.float :standard_trio_odds680
      t.float :standard_trio_odds681
      t.float :standard_trio_odds682
      t.float :standard_trio_odds683
      t.float :standard_trio_odds684
      t.float :standard_trio_odds685
      t.float :standard_trio_odds686
      t.float :standard_trio_odds687
      t.float :standard_trio_odds688
      t.float :standard_trio_odds689
      t.float :standard_trio_odds690
      t.float :standard_trio_odds691
      t.float :standard_trio_odds692
      t.float :standard_trio_odds693
      t.float :standard_trio_odds694
      t.float :standard_trio_odds695
      t.float :standard_trio_odds696
      t.float :standard_trio_odds697
      t.float :standard_trio_odds698
      t.float :standard_trio_odds699
      t.float :standard_trio_odds700
      t.float :standard_trio_odds701
      t.float :standard_trio_odds702
      t.float :standard_trio_odds703
      t.float :standard_trio_odds704
      t.float :standard_trio_odds705
      t.float :standard_trio_odds706
      t.float :standard_trio_odds707
      t.float :standard_trio_odds708
      t.float :standard_trio_odds709
      t.float :standard_trio_odds710
      t.float :standard_trio_odds711
      t.float :standard_trio_odds712
      t.float :standard_trio_odds713
      t.float :standard_trio_odds714
      t.float :standard_trio_odds715
      t.float :standard_trio_odds716
      t.float :standard_trio_odds717
      t.float :standard_trio_odds718
      t.float :standard_trio_odds719
      t.float :standard_trio_odds720
      t.float :standard_trio_odds721
      t.float :standard_trio_odds722
      t.float :standard_trio_odds723
      t.float :standard_trio_odds724
      t.float :standard_trio_odds725
      t.float :standard_trio_odds726
      t.float :standard_trio_odds727
      t.float :standard_trio_odds728
      t.float :standard_trio_odds729
      t.float :standard_trio_odds730
      t.float :standard_trio_odds731
      t.float :standard_trio_odds732
      t.float :standard_trio_odds733
      t.float :standard_trio_odds734
      t.float :standard_trio_odds735
      t.float :standard_trio_odds736
      t.float :standard_trio_odds737
      t.float :standard_trio_odds738
      t.float :standard_trio_odds739
      t.float :standard_trio_odds740
      t.float :standard_trio_odds741
      t.float :standard_trio_odds742
      t.float :standard_trio_odds743
      t.float :standard_trio_odds744
      t.float :standard_trio_odds745
      t.float :standard_trio_odds746
      t.float :standard_trio_odds747
      t.float :standard_trio_odds748
      t.float :standard_trio_odds749
      t.float :standard_trio_odds750
      t.float :standard_trio_odds751
      t.float :standard_trio_odds752
      t.float :standard_trio_odds753
      t.float :standard_trio_odds754
      t.float :standard_trio_odds755
      t.float :standard_trio_odds756
      t.float :standard_trio_odds757
      t.float :standard_trio_odds758
      t.float :standard_trio_odds759
      t.float :standard_trio_odds760
      t.float :standard_trio_odds761
      t.float :standard_trio_odds762
      t.float :standard_trio_odds763
      t.float :standard_trio_odds764
      t.float :standard_trio_odds765
      t.float :standard_trio_odds766
      t.float :standard_trio_odds767
      t.float :standard_trio_odds768
      t.float :standard_trio_odds769
      t.float :standard_trio_odds770
      t.float :standard_trio_odds771
      t.float :standard_trio_odds772
      t.float :standard_trio_odds773
      t.float :standard_trio_odds774
      t.float :standard_trio_odds775
      t.float :standard_trio_odds776
      t.float :standard_trio_odds777
      t.float :standard_trio_odds778
      t.float :standard_trio_odds779
      t.float :standard_trio_odds780
      t.float :standard_trio_odds781
      t.float :standard_trio_odds782
      t.float :standard_trio_odds783
      t.float :standard_trio_odds784
      t.float :standard_trio_odds785
      t.float :standard_trio_odds786
      t.float :standard_trio_odds787
      t.float :standard_trio_odds788
      t.float :standard_trio_odds789
      t.float :standard_trio_odds790
      t.float :standard_trio_odds791
      t.float :standard_trio_odds792
      t.float :standard_trio_odds793
      t.float :standard_trio_odds794
      t.float :standard_trio_odds795
      t.float :standard_trio_odds796
      t.float :standard_trio_odds797
      t.float :standard_trio_odds798
      t.float :standard_trio_odds799
      t.float :standard_trio_odds800
      t.float :standard_trio_odds801
      t.float :standard_trio_odds802
      t.float :standard_trio_odds803
      t.float :standard_trio_odds804
      t.float :standard_trio_odds805
      t.float :standard_trio_odds806
      t.float :standard_trio_odds807
      t.float :standard_trio_odds808
      t.float :standard_trio_odds809
      t.float :standard_trio_odds810
      t.float :standard_trio_odds811
      t.float :standard_trio_odds812
      t.float :standard_trio_odds813
      t.float :standard_trio_odds814
      t.float :standard_trio_odds815
      t.float :standard_trio_odds816

      t.timestamps
    end
  end
end
